 ----------------------------------------
 #35 - Rethrow Exception
 ----------------------------------------
 try
 {
	DoSomeMath();
 }
 catch(ArithmeticException e)
 {
	Console.WriteLine("Hmm There was an error in there, be careful!");
 }
 
 Console.ReadLine();
 
 public void DoSomeMath()
 {
	int x = 10;
	int y = 0;
	int result;
	try
	{
		result = x/y;
	}
	catch
	{
		Console.WriteLine("Error in Do SomeMath()");
		throw new ArithmeticException();
	}

 }